version: "3.8"

services:
  app:
    build: .
    ports:
      - "8080:8080"
    environment:
      PORT: 8080
      DNS_DOCKER: "root:root@tcp(mysql:3306)/test?charset=utf8mb4&parseTime=True&loc=Local"
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
